### ISSUE TITLE
Center capitals?

### ISSUE THREAD

**Issue by RosaWagner** [KanonFoundry/HedvigLetters#3]
For latin fonts we recommend to center capitals vertically to simplify UI design. To achieve that you can set the vertical metric values to have the same amount of space above and under the capitals.

**Comment by KanonFoundry** [comment]
I've just updated the metrics in all the files, but I thought you might want to have a look at the values to see if it's good. 
I usually do the metrics in a different way, so if you would like to check if it's up to standard I'd appreciate it! :)

**Comment by RosaWagner** [comment]
It looks fine, thanks
